#include "STD_TYPES.h"
#include "GPIO.h"
#include "LED.h"


const LED_MAP_t  map[NUM_OF_LEDS]={{ALARM_LED     ,GPIO_PIN12_MASK,OUTPUT_10MHz_PUSH_PULL,ACTIVE_HIGH,GPIO_PORTC}
                            ,{BUZZER_LED    ,(GPIO_PIN14_MASK | GPIO_PIN15_MASK),OUTPUT_10MHz_PUSH_PULL,ACTIVE_HIGH,GPIO_PORTC}};


const GPIO_t LEDS[NUM_OF_LEDS] = {{GPIO_PIN13_MASK,OUTPUT_10MHz_PUSH_PULL,GPIO_PORTC}
		                   ,{(GPIO_PIN14_MASK | GPIO_PIN15_MASK) ,OUTPUT_10MHz_PUSH_PULL,GPIO_PORTC}};
